### ISSUE TITLE
The last regexp of question_jp.hed is ineffective.

### ISSUE THREAD

**Issue by taroushirani** [r9y9/nnmnkwii_gallery#14]
The last CQS of question_jp.hed (for 'k3') contains escaped "$" to match the last char of line, but it is escaped as ('\\-(\\d+)\\\\\\$') by  wildcards2regex in nnmnkwii.io.hts and does not match to 'k3' label.

I have no idea about the importance of 'k3' but this may have little effect on dnn synthesis, though.

https://gist.github.com/taroushirani/16bc581ab737ccc4ede80feb94c81620

**Comment by taroushirani** [comment]
The number of backslash was corrected by github when I posted so please see the my gist for detail.

**Comment by r9y9** [comment]
Thanks for catching this. You are right. Fixed by https://github.com/r9y9/nnmnkwii_gallery/commit/ddc6b2d5df4bdfd013a9ba948b30724e4ec41170

According to lab_format.pdf in HTS-jp demo, the context k3 means `the number of moras in this utterance`. I don't think the utterance-wise context is helpful for modeling linguistic-acoustic feature relationship. We can simply remove it, but I will keep it as is for now.

**Comment by r9y9** [comment]
I am closing this issue. Feel free to reopen if the problem persists.
